# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-08 18:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotedriver', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='list',
            old_name='name',
            new_name='lastname',
        ),
    ]
