# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-10 01:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotedriver', '0005_list_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='title',
            field=models.CharField(max_length=30),
        ),
    ]
