# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-10 01:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotedriver', '0008_auto_20180210_0129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='text',
            field=models.TextField(max_length=1000),
        ),
    ]
