# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-14 05:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quotedriver', '0012_auto_20180214_0449'),
    ]

    operations = [
        migrations.RenameModel('Card', 'Quote'),
    ]
