# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-14 05:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotedriver', '0014_auto_20180214_0516'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='List',
            new_name='Author',
        ),
        migrations.AlterModelOptions(
            name='quote',
            options={'ordering': ['author', 'category']},
        ),
        migrations.RenameField(
            model_name='quote',
            old_name='list',
            new_name='author',
        ),
    ]
