# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-14 07:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotedriver', '0015_auto_20180214_0549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='text',
            field=models.TextField(max_length=10000),
        ),
    ]
