# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-09 02:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrumboard', '0003_auto_20180208_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='firstname',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='list',
            name='lastname',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='list',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
