# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-10 01:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrumboard', '0006_auto_20180210_0124'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='title',
            new_name='category',
        ),
    ]
