# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-10 07:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrumboard', '0010_auto_20180210_0447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='firstname',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='list',
            unique_together=set([('firstname', 'lastname')]),
        ),
    ]
